grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: admin

prometheus:
  enabled: true
  pushgateway:
    enabled: false
  server:
    service:
      type: LoadBalancer
      servicePort: 9090

promtail:
  image:
    pullPolicy: Never

loki:
  image:
    pullPolicy: Never
  service:
    type: LoadBalancer